---
- name: Add deb non-free and contrib into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian/ bullseye non-freea contrib
- name: Add deb-src non-free and contrib into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb-src http://deb.debian.org/debian/ bullseye non-free contrib
- name: Install iwlwifi firmware
  become: yes
  apt:
    name: firmware-iwlwifi
    update_cache: yes
- name: Load iwlwifi firmware
  become: yes
  community.general.modprobe:
    name: iwlwifi
    state: present

- name: Install basic packages
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
    - firmware-linux
    - firmware-realtek
    - intel-microcode
    - lightdm
    - network-manager
    - net-tools
    - tmux
    - ssh
    - zsh
    - fzf
    - bat
    - arandr
    - apt-transport-https
    - curl
    - ranger
    - nitrogen
    - zathura
    - sxiv
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - gnome-terminal
    - feh
    - xinit
    - xorg
    - xfce4-session
    - docker.io
    - docker-compose
    - git
    - gcc
    - g++
    - make
    - cmake
    - python3
    - python3-pip
    - python3-dev
    - ipython3
    - wireshark
    - clang-format
    - clang
    - fonts-powerline
    - htop
    - tig
    - flameshot
    - ffmpeg
    - mumble
    - pavucontrol
    - npm
    - libboost-all-dev
    - apt-transport-https
    - xsel
    - silversearcher-ag
    - gpg
    - x2goclient
  become: yes

- name: Install python packages
  pip:
    name: "{{ item }}"
    executable: pip3
    virtualenv_python: /usr/bin/python3
  loop:
    - jedi
    - flake8
    - autokey
    - elasticsearch
    - requests
    - redis
    - urllib3
    - PyYAML
    - matplotlib
    - autopep8
    - pylint
    - wheel

- name: Make config directory
  ansible.builtin.file:
    path: ~/.config
    state: directory

- name: Get path to ohhmyzsh
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_dir

- name: Install ohhmyzsh
  when: not ohmyzsh_dir.stat.exists
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Clone fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1

- name: Install fzf
  ansible.builtin.command: ~/.fzf/install
