---
- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
    - i3
    - i3lock
    - dmenu
    - polybar
    - rofi
    - xinit
    - xorg
    - xfce4-session
    - i3blocks
  become: yes

- name: Clone config
  ansible.builtin.git:
    repo: https://github.com/Gr4b4rz/i3-config.git
    dest: ~/i3-config

- name: Copy fonts to system dir
  ansible.builtin.copy:
    src: ~/i3-config/fonts/
    dest: /usr/share/fonts/
  become: yes

- name: Load fonts
  ansible.builtin.shell: fc-cache -vf /usr/share/fonts

- name: Make i3 config directory
  ansible.builtin.file:
    path: ~/.config/i3
    state: directory

- name: Copy i3 config
  ansible.builtin.copy:
    src: ~/i3-config/config
    dest: ~/.config/i3/

- name: Copy zshrc
  ansible.builtin.copy:
    src: ~/i3-config/zshrc
    dest: ~/.zshrc

- name: Copy ranger config files
  ansible.builtin.copy:
    src: ~/i3-config/ranger
    dest: ~/.config/

- name: Changing perm of ranger's scope.sh - adding "+x"
  file:
    path: ~/.config/ranger/scope.sh
    mode: a+x

- name: Copy polybar config files
  ansible.builtin.copy:
    src: ~/i3-config/polybar
    dest: ~/.config/

- name: Setup gnome-terminal
  ansible.builtin.shell: ~/i3-config/gnome_terminal/setup_terminal.sh

- name: Change user's shell and generate ssh keys
  ansible.builtin.user:
    name: pgrabarski
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_type: ed25519
  become: true

- name: Change root's shell
  ansible.builtin.user:
    name: root
    shell: /bin/zsh
  become: true
