---
- name: Download brave gpg
  become: yes
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
- name: Add brave repository to source list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    filename: brave-browser-release
- name: Install brave package
  become: yes
  apt:
    name: brave-browser
    update_cache: yes
