---
- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
    - vim
    - neovim
    - ccls
    - nodejs
  become: yes

- name: Clone config
  ansible.builtin.git:
    repo: https://github.com/Gr4b4rz/vim-config.git
    dest: ~/vim-config

- name: Copy vimrc to default directory
  ansible.builtin.copy:
    src: ~/vim-config/vimrc
    dest: ~.vimrc

- name: Copy nvim config to default directory
  ansible.builtin.copy:
    src: ~/vim-config/nvim
    dest: ~./config/
