---
- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
    - vim
    - neovim
    - ccls
    - nodejs
  become: yes

- name: Clone config
  ansible.builtin.git:
    repo: https://github.com/Gr4b4rz/vim-config.git
    dest: ~/vim-config

- name: Copy vimrc to default directory
  ansible.builtin.copy:
    src: ~/vim-config/vimrc
    dest: ~/.vimrc

- name: Copy nvim config to default directory
  ansible.builtin.copy:
    src: ~/vim-config/nvim
    dest: ~/.config/

- name: Install vim-plug
  ansible.builtin.shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: Install neovim plugins
  ansible.builtin.shell: nvim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty

- name: Install CoC extensions
  ansible.builtin.shell: ~/vim-config/coc/install_extensions.sh
